development:
  SECRET_KEY: 'sk_test_51KRSa9SBsGsaYp6jO2uiNA4cKdShYR7CEUKPrvmp48SkWwcpz9Y9T169ouwYkIkQKI9SBVTxWv4gU0qbSLUYGSdh00ISn7JTz2'
  PUBLISHABLE_KEY: 'pk_test_51KRSa9SBsGsaYp6jRDV3mfVAF2oyjXWHNmxbjvPRnXzWxB4tHfJGBVhNp9oqQjQrX2kVm8PBauuGXY4wXKCC3B2u00CMFEosMl'